apiVersion: v1
kind: PersistentVolume
metadata: 
  name: {{ .Values.pvName }}
  labels: 
    vol: {{ .Values.pvLabel }}
spec: 
  capacity:
    storage: {{ .Values.pvStorage }}
  accessModes:
    - {{ .Values.pvAccessModes }} 
  hostPath:
    path: {{ .Values.pvPath }}
