apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: {{ .Values.pvcName }}
spec: 
  accessModes:
    -  {{ .Values.pvAccessModes }}
  resources:
    requests:
      storage: {{ .Values.pvStorage }}
  selector:
    matchLabels:
      vol: {{ .Values.pvLabel }}
