apiVersion: v1
kind: Service
metadata: 
 name: wordpress-service
 labels:
  app: wordpress
spec:
 type: NodePort
 ports: 
   - port: {{ .Values.wordpressLocalPort }}
     nodePort: {{ .Values.wordpressContainerPort }}
 selector:
    app: wordpress
