apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    {{- include "wordpress_app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.wordpressReplicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wordpress_app.selectorLabels" . | nindent 8 }}
        app: wordpress
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      strategy:
        type: {{ .Values.wordpressUpdateStrategy }}
      serviceAccountName: {{ include "wordpress_app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.wordpressImageName }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.wordpressImage.repository }}:{{ .Values.wordpressImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.wordpressImage.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
#          livenessProbe:
#            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
#            httpGet:
#              path: /
#              port: http
          env: 
            - name: WORDPRESS_DB_HOST
              value: {{ .Values.wordpressDbHost }}
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  key: dbuser
                  name: app-secret
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: dbpass
                  name: app-secret
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef: 
                  key: dbname
                  name: app-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
